### ISSUE TITLE
Tri

### ISSUE THREAD

**Issue by GulKK** [CollegeBoreal/INF1042-17H#10]
Bonsoir Mr, c'est pour mon projet je vous prie de regarder puis 
me dire les erreurs et la marche et aussi IntelliJidea ne compile pas ça ecrit que scala ne pas
 en mode SDK comment puis-je resoudre ? Merci (GuiKK)

**Comment by setrar** [comment]
Je ne vois pas ton code.
Peux tu faire un commit et le pousser pour que je puisse t'aider?

**Comment by setrar** [comment]
Peux-tu faire un commit et un push de ton code?

Je vais verifier ce qui ne va pas avant notre rencontre de demain.

Quand on se verra il sera trop tard pour faire des modifications.

Meme si ca ne compile pas!
