### ISSUE TITLE
check on

### ISSUE THREAD

**Issue by sowmdou0968** [CollegeBoreal/INF1042-17H#8]
les dernier code a rectifier

**Comment by setrar** [comment]
1) Vérifie le code, il a 3 fonctions et les trois fonctions ne retournent rien (i.e. Unit)
2) Dans la fonction count, la ligne ci-dessous est en Java donc ne compile pas
_int result = (int) set + (int) (set >>> 32)_
3) Commence tes tests 
     Appelles _Bits_ dans _main_ pour sefaire tu dois changer la _class_ Bits en _objet_

**Comment by setrar** [comment]
le point 1. les fonctions ne retournent rien! Il faut un signe egal
