### ISSUE TITLE
de la part de Rassoul Ba a monsieur BRICE ROBERT

### ISSUE THREAD

**Issue by bilguisse** [CollegeBoreal/INF1042-17H#9]
MONSIEUR POUVEZ VOUS REGARDER MON PROJET DANS LE MAIN CAR JE N ARRIVE PAS A LE FAIRE COMPILER

**Comment by setrar** [comment]
La definition de ta classe Cercle a un probleme.

Ou est le debut et la fin? Pourquoi il y en a deux?
